matrix:
  include:
    - language: java
      before_install:
        - cd api
      install: true
      script: mvn clean install
    - language: node_js
      node_js: "6"
      before_install:
        - cd ui
notifications:
  email: false
