jobs:
  include:
    - stage: test
      name: api test
      language: java
      jdk: oraclejdk8
      services:
        - docker
      before_install:
        - cd api
      install: true
      script: mvn clean install
    - stage: test
      name: ui test
      language: node_js
      node_js: "8"
      before_install:
        - cd ui
    - stage: deploy api
      script: skip
      deploy:
        provider: elasticbeanstalk
        on:
          all_branches: true
        access_key_id: access_key_id
        secret_access_key:
          secure: secret_access_key
        region: ap-southeast-2  
        app: Glue Stack
        env: GlueStack-env
        bucket_name: elasticbeanstalk-ap-southeast-2-019794990741
        zip_file: api/target/api-0.0.1-SNAPSHOT.jar
    - stage: deploy ui
      script: skip
      deploy:
        provider: s3
        on:
          all_branches: true
        access_key_id: access_key_id
        secret_access_key: secret_access_key
        bucket: gluestack
        region: ap-southeast-2
        skip_cleanup: true
        local_dir: ui/build
notifications:
  email: false
