jobs:
  include:
  - stage: test
    name: api test
    language: java
    jdk: oraclejdk8
    services:
    - docker
    before_install:
    - cd api
    install: true
    script: mvn clean install
  - stage: test
    name: ui test
    language: node_js
    node_js: '8'
    before_install:
    - cd ui
    install: yarn
    script: yarn test
  - stage: deploy api
    language: java
    jdk: oraclejdk8
    services:
    - docker
    before_install:
    - cd api
    install: true
    script: mvn package -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    deploy:
      provider: elasticbeanstalk
      skip_cleanup: true
      on:
        all_branches: true
      access_key_id: access_key_id
      secret_access_key:
        secure: secret_access_key
      region: ap-southeast-2
      app: Glue Stack
      env: GlueStack-env
      bucket_name: elasticbeanstalk-ap-southeast-2-019794990741
      zip_file: target/api-0.0.1-SNAPSHOT.jar
  - stage: deploy ui
    language: node_js
    node_js: '8'
    before_install:
    - cd ui
    install: yarn
    script: yarn build
    deploy:
      provider: s3
      skip_cleanup: true
      on:
        all_branches: true
      access_key_id: access_key_id
      secret_access_key: secret_access_key
      bucket: gluestack
      region: ap-southeast-2
      local_dir: build
notifications:
  email: false
env:
  secure: QE2pVPy8FYZdc0dFB3uuGZw5UQ5doMbgV/Ulqtr/5FfLFqcttiyV7GGL7AyegprN/FYcrvSasacrOQPsOsZ8lMRrL3A45cO2sdiBMv9GQ4M2i+TohxejzGAE1QgD9LyoMpC34EaKQ9UxcddQNbW9I8JiXS/7StELcagEpIAehzKYsJj/qC8Uqd2sFqlatnfc5TfftjEKrqn4kuDeS0wcGrCKiRiBqy2Br35afL/3YsN2h0cChiXYR2U3PatiKXtu+kbehi8YLv8LIyTib9wZt+CHOOCrNlYjPvIiL1XfafxFLo7BCz6z3ugjJ7c8hgDqNouWJtQn/YVuLj9Ztp8R/ueslU18zmIM+yQ5uNVTj7NbgjTIgKkUks8eEviBFOw4By5TwwPWSeQ9J0c6qO69gGr6s97ffxUieGiNK5QXWRbGTouEqDlpE7jixHwK3h5ClgjQPNVpA2bHL8aUd0rdY4XXhH9tyiV1XQlqYLF4qZWt3h8zriBKA4De6Pn/D7PfelbNIZlV5OSh7zoI9tFW8bubdBuIsAeQH7l6Gr3ebL0/Nqz4+iY+Lz4LHQjQcYY6hLADkfY0PA7meHg+tOAKDAdUmc5Q1sqTF9eCm0bDv66iA43vYhNUKVW+LZq9LHRgi8lUHyVUaAUdD5HVb5qcBHFTM6gOVjeUev8btaY4Rks=
