version: '3'
services:
  database:
    image: mysql/mysql-server:5.7.21
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "glue"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_HOST: "%"
  app:
    build: .
    depends_on:
      - database
    ports:
      - "8080:8080"
    environment:
      RDS_HOSTNAME: database
      RDS_PORT: 3306
      RDS_DB_NAME: glue
      RDS_USERNAME: root
      RDS_PASSWORD: 