name: Pull Request
on:
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Google Cloud
      uses: actions/gcloud/auth@master
      env:
        GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
    - name: build
      uses: actions/gcloud/cli@master
      working-directory: devops
      run: sh ./1-build.sh
    - name: deploy-staging
      uses: actions/gcloud/cli@master
      working-directory: devops
      run: sh ./2-deploy-staging.sh
